version: '3.9'

services:
  localstack:
    image: localstack/localstack
    ports:
      - ${LOCALSTACK_PORT}:${LOCALSTACK_PORT}
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  s3_setup:
    image: localstack/localstack
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: ["aws", "--endpoint-url", "http://localstack:4566", "s3api", "create-bucket", "--bucket", "${S3_BUCKET}"]
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  spark:
    build:
      context: .
      dockerfile: ./Spark3/Dockerfile.dev
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./Spark3/apps:/opt/spark-apps
       - ./Spark3/data:/opt/spark-data
    #environment:
      # - SPARK_LOCAL_IP=${SPARK_MASTER_IP}
      # - SPARK_WORKLOAD=master
  spark-worker:
    build:
      context: .
      dockerfile: ./Spark3/DockerfileW.dev
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark
    environment:
      - SPARK_MASTER=spark://spark:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=256M
      - SPARK_DRIVER_MEMORY=256M
      - SPARK_EXECUTOR_MEMORY=256M
      # - SPARK_WORKLOAD=worker
      # - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data

  app:
    build:
      context: .
      dockerfile: ./hive-metastore/Dockerfile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_ENDPOINT_URL=http://localstack:${LOCALSTACK_PORT}
      - S3_BUCKET
      - S3_PREFIX
    ports:
      - '9083:9083'

  test:
    image: python:3.10-alpine
    depends_on:
      app:
        condition: service_healthy
    command: ["./test.sh"]
    profiles:
      - dev
    working_dir: /scripts
    volumes:
      - ./scripts:/scripts
    environment:
      - HIVE_HOST=app
      - HIVE_PORT=9083
